commit_message: "%language% translation for %original_file_name% [skip ci]"
append_commit_message: false

files:
  - source: /localization/rssguard_en.ts
    translation: /localization/rssguard_%locale_with_underscore%.ts
